# Default initial positions for panda's ros2_control fake system

initial_positions:
  panda_1_finger_joint1: 0
  panda_1_joint1: 0
  panda_1_joint2: 0
  panda_1_joint3: 0
  panda_1_joint4: 0
  panda_1_joint5: 0
  panda_1_joint6: 0
  panda_1_joint7: 0
  panda_2_finger_joint1: 0
  panda_2_joint1: 0
  panda_2_joint2: 0
  panda_2_joint3: 0
  panda_2_joint4: 0
  panda_2_joint5: 0
  panda_2_joint6: 0
  panda_2_joint7: 0