# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_2_controller
    - panda_1_controller
    - hand_1_controller
    - hand_2_controller

  panda_2_controller:
    type: FollowJointTrajectory
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  panda_1_controller:
    type: FollowJointTrajectory
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  hand_1_controller:
    type: GripperCommand
    joints:
      - panda_1_finger_joint1
    action_ns: gripper_cmd
    default: true
  hand_2_controller:
    type: GripperCommand
    joints:
      - panda_2_finger_joint1
    action_ns: gripper_cmd
    default: true