# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hand_1_controller:
      type: position_controllers/GripperActionController


    hand_2_controller:
      type: position_controllers/GripperActionController


    panda_2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hand_1_controller:
  ros__parameters:
    joint: panda_1_finger_joint1
hand_2_controller:
  ros__parameters:
    joint: panda_2_finger_joint1
panda_2_controller:
  ros__parameters:
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
panda_1_controller:
  ros__parameters:
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity